// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/Login": {
            "get": {
                "description": "用户登录使用JWT验证",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户登录验证",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户密码",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/def.ResponseForm"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/def.ResponseForm"
                        }
                    }
                }
            }
        },
        "/api/ListCollectedJobs": {
            "get": {
                "description": "列出用户收藏的工作",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作管理"
                ],
                "summary": "列出用户收藏的工作",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "将要列出收藏工作的用户UserId",
                        "name": "UserId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/def.ResponseForm"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/def.ResponseForm"
                        }
                    }
                }
            }
        },
        "/api/ListUploadedJobs": {
            "get": {
                "description": "列出用户已上传的工作",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作管理"
                ],
                "summary": "列出用户已上传的工作",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "将要列出工作的用户UserId",
                        "name": "UserId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/ListViewedJobs": {
            "get": {
                "description": "列出最近浏览的工作",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作管理"
                ],
                "summary": "列出最近浏览的工作",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "将要列出最近浏览的用户UserId",
                        "name": "UserId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/def.ResponseForm"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/def.ResponseForm"
                        }
                    }
                }
            }
        },
        "/api/jobs/collect": {
            "post": {
                "description": "对某一工作进入收藏夹",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作管理"
                ],
                "summary": "收藏工作",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/def.CollectJobRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/def.ResponseForm"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/def.ResponseForm"
                        }
                    }
                }
            }
        },
        "/api/jobs/de-collect": {
            "post": {
                "description": "对某一工作取消收藏",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作管理"
                ],
                "summary": "取消收藏工作",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/def.CollectJobRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/def.ResponseForm"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/def.ResponseForm"
                        }
                    }
                }
            }
        },
        "/api/jobs/polish": {
            "post": {
                "description": "对多个工作进行高亮标注",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作管理"
                ],
                "summary": "批量擦亮工作",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/def.BatchPolishJobsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/def.ResponseForm"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/def.ResponseForm"
                        }
                    }
                }
            }
        },
        "/api/jobs/pull-off": {
            "post": {
                "description": "将选中的工作进行下架",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作管理"
                ],
                "summary": "批量下架工作",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/def.BatchPullOffJobsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/def.ResponseForm"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/def.ResponseForm"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "def.BatchPolishJobsRequest": {
            "type": "object",
            "properties": {
                "jobIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "def.BatchPullOffJobsRequest": {
            "type": "object",
            "properties": {
                "jobIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "def.CollectJobRequest": {
            "type": "object",
            "properties": {
                "jobId": {
                    "type": "string"
                }
            }
        },
        "def.ResponseForm": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
