definitions:
  def.BatchPolishJobsRequest:
    properties:
      jobIds:
        items:
          type: string
        type: array
    type: object
  def.BatchPullOffJobsRequest:
    properties:
      jobIds:
        items:
          type: string
        type: array
    type: object
  def.CollectJobRequest:
    properties:
      jobId:
        type: string
    type: object
  def.ResponseForm:
    properties:
      code:
        type: string
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /Login:
    get:
      description: 用户登录使用JWT验证
      parameters:
      - description: 用户ID
        in: query
        name: name
        required: true
        type: string
      - description: 用户密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/def.ResponseForm'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/def.ResponseForm'
      summary: 用户登录验证
      tags:
      - 用户管理
  /api/ListCollectedJobs:
    get:
      description: 列出用户收藏的工作
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 将要列出收藏工作的用户UserId
        in: query
        name: UserId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/def.ResponseForm'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/def.ResponseForm'
      summary: 列出用户收藏的工作
      tags:
      - 工作管理
  /api/ListUploadedJobs:
    get:
      description: 列出用户已上传的工作
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 将要列出工作的用户UserId
        in: query
        name: UserId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 列出用户已上传的工作
      tags:
      - 工作管理
  /api/ListViewedJobs:
    get:
      description: 列出最近浏览的工作
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 将要列出最近浏览的用户UserId
        in: query
        name: UserId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/def.ResponseForm'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/def.ResponseForm'
      summary: 列出最近浏览的工作
      tags:
      - 工作管理
  /api/jobs/collect:
    post:
      description: 对某一工作进入收藏夹
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/def.CollectJobRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/def.ResponseForm'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/def.ResponseForm'
      summary: 收藏工作
      tags:
      - 工作管理
  /api/jobs/de-collect:
    post:
      description: 对某一工作取消收藏
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/def.CollectJobRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/def.ResponseForm'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/def.ResponseForm'
      summary: 取消收藏工作
      tags:
      - 工作管理
  /api/jobs/polish:
    post:
      consumes:
      - application/json
      description: 对多个工作进行高亮标注
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/def.BatchPolishJobsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/def.ResponseForm'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/def.ResponseForm'
      summary: 批量擦亮工作
      tags:
      - 工作管理
  /api/jobs/pull-off:
    post:
      description: 将选中的工作进行下架
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/def.BatchPullOffJobsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/def.ResponseForm'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/def.ResponseForm'
      summary: 批量下架工作
      tags:
      - 工作管理
swagger: "2.0"
